server:
  port: 8083
spring:
  application:
    name: pricing-service
  datasource:
    url: jdbc:mysql://localhost:3306/ms_pricingdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
