server:
  port: 8085
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ms_productdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      pricingService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000ms
